### ISSUE TITLE
Change/Add group join codes

### ISSUE THREAD

**Issue by bradwj** [bradwj/friend-advisor#25]
Generate smaller join codes for groups that make it easier for users to join.

**Comment by demonlexe** [comment]
The creation of the code and assignment to a newly created group is complete. If the code cannot create an un-used code within 50 tries, it will set the joinId of the new group to "".

To Do: 
- Add endpoint for obtaining the joinId for a group 
- Incorporate new joinId system into frontend code

**Comment by bradwj** [comment]
I don't think generating a join code should ever fail. Every group should have a join code, so if it takes over 50 tries to generate a code then we may need a new way of doing it.

**Comment by demonlexe** [comment]
Issue Optimized and Solved.

The function has been moved to createjoincode.js and: 
A - it only gathers group data once
B - if it can't find an unused code within 50 generated codes, it will go up by one character (e.g. if all 6 digit codes are used up, it will make a 7 digit code, etc) 

To Do:
Implement utilization with front-end.

**Comment by demonlexe** [comment]
@realprogrammer5000 I have assigned you to this issue, let me know if there are issues implementing from the frontend.

I have created documentation, please load it into https://editor.swagger.io/#

**Comment by realprogrammer5000** [comment]
Should be good now, fixed with #35
