### ISSUE TITLE
Clean-Up Scheduler

### ISSUE THREAD

**Issue by demonlexe** [bradwj/friend-advisor#32]
We could add a function to the notification scheduler that will do the following:
- remove events from groups that don't exist
- remove groups that have no members
- remove groups whose joinId was not generated (The function will set the joinId to "" if it cannot create an id within 50 attempts)

**Comment by bradwj** [comment]
I think it would be better if we didn't use a scheduler for this. 
For example, when a request is sent to the backend for a user to be removed from a group, we can check if there are no users in the group after the user is removed, and then call the function to delete the group itself.

**Comment by demonlexe** [comment]
Maybe we can:

This will make it so that the existing IDs are only gathered ONCE from database, as opposed to each iteration.
Furthermore, if it cannot generate an un-used code within 10 tries, it will add an extra character slot until a code is found within 10 tries.

Pseudocode:

function createUnusedId() {      //returns a code
    const existingIds = getAllExistingIds();
    let idLength = 7;
    let attempts = 1;
    let unusedIdToReturn = null;
    
    loop until  unusedIdToReturn != null
    {
      let attemptId = generateId(idLength);
      for existingIds (id)
        {
        if (id == attemptId) then { attemptId = null; break out of inner loop }
        }
      unusedIdToReturn = attemptId
      attempts ++;
      if (attempts >= 10) { idLength ++;}
    }
}
